CODE_NOT_SET = 'NOT_SET_CODE'
UNDEFINED_STRING = 'UNDEFINED_STRING'
UNDEFINED_VALUE = -1

GUDID_ZIP_FILE_NAME = 'GUDID_full_release.zip'
GUDID_FOLDER_NAME = 'GUDID_full_release'
TOP_LEVEL = 'TOP LEVEL'
RANDOM_SEED_INT = 42

X_TICKS_SIZE = 22
Y_TICKS_SIZE = 22
X_LABEL_SIZE = 24
Y_LABEL_SIZE = 24
TITLE_SIZE = 26
MATRIX_NUMBER_SIZE = 21