import os

current_directory_path = os.getcwd().replace('\\', '/')

if current_directory_path.__contains__('/src'):
    code_directory_index = current_directory_path.find('src')
else:
    code_directory_index = current_directory_path.find('/tests') + 1

FILES_DIRECTORY = current_directory_path[:code_directory_index] + "application_files/"

SOURCE_DATA_DIRECTORY_PATH = FILES_DIRECTORY + 'SourceData/'
GUDID_FULL_RELEASE_DIRECTORY_PATH = SOURCE_DATA_DIRECTORY_PATH + 'GUDID_full_release/'

OUTPUT_DATA_DIRECTORY_PATH = FILES_DIRECTORY + 'OutputData/'
LOGGING_DIRECTORY_PATH = OUTPUT_DATA_DIRECTORY_PATH + 'Logging/'
MODELS_DIRECTORY_PATH = OUTPUT_DATA_DIRECTORY_PATH + 'Models/'
SQL_CSV_TABLES_DIRECTORY_PATH = OUTPUT_DATA_DIRECTORY_PATH + 'SqlCsvTables/'
COMPUTATION_FILES_DIRECTORY_PATH = OUTPUT_DATA_DIRECTORY_PATH + 'ComputationFiles/'
VALIDATION_RESULTS_DIRECTORY_PATH = OUTPUT_DATA_DIRECTORY_PATH + 'ValidationResults/'

GMDN_EMDN_VALIDATION_DIRECTORY_PATH = VALIDATION_RESULTS_DIRECTORY_PATH + 'GmdnEmdn/'

PIPELINE_COMPUTATION_DIRECTORY_PATH = COMPUTATION_FILES_DIRECTORY_PATH + 'PipelineComputation/'

DIRECTORIES = [
    FILES_DIRECTORY,
    SOURCE_DATA_DIRECTORY_PATH,
    GUDID_FULL_RELEASE_DIRECTORY_PATH,
    OUTPUT_DATA_DIRECTORY_PATH,
    LOGGING_DIRECTORY_PATH,
    MODELS_DIRECTORY_PATH,
    SQL_CSV_TABLES_DIRECTORY_PATH,
    COMPUTATION_FILES_DIRECTORY_PATH,
    VALIDATION_RESULTS_DIRECTORY_PATH,
    GMDN_EMDN_VALIDATION_DIRECTORY_PATH,
    PIPELINE_COMPUTATION_DIRECTORY_PATH,
]
