from src.__directory_paths import SOURCE_DATA_DIRECTORY_PATH, OUTPUT_DATA_DIRECTORY_PATH, SQL_CSV_TABLES_DIRECTORY_PATH

EMDN_FILE_PATH = SOURCE_DATA_DIRECTORY_PATH + 'EMDN.csv'

NEW_ITALIAN_FULL_CSV_PATH = SOURCE_DATA_DIRECTORY_PATH + 'italian_medical_device_full_list_cleaned.csv'
OLD_ITALIAN_FULL_PATH = SOURCE_DATA_DIRECTORY_PATH + 'italian_medical_device_full_list.csv'
NEW_AMERICAN_CSV_FULL_PATH = OUTPUT_DATA_DIRECTORY_PATH + 'new_american_medical_device_full_list.csv'

EMDN_GMDN_FDA_FILE_PATH = SQL_CSV_TABLES_DIRECTORY_PATH + 'emdn_gmdn_fda.csv'
MEDICAL_SPECIALTY_FILE_PATH = SOURCE_DATA_DIRECTORY_PATH + 'medical_specialties.csv'
EMDN_GMDN_FDA_CLEANED_FILE_PATH = OUTPUT_DATA_DIRECTORY_PATH + 'emdn_gmdn_fda_cleaned.csv'
TRAIN_FILE_PATH = OUTPUT_DATA_DIRECTORY_PATH + 'train.csv'
TEST_FILE_PATH = OUTPUT_DATA_DIRECTORY_PATH + 'test.csv'
